export const languages = {
  Bulgarian: 'BG',
  Czech: 'CS',
  Danish: 'DA',
  German: 'DE',
  Greek: 'EL',
  English: 'EN',
  Spanish: 'ES',
  Estonian: 'ET',
  Finnish: 'FI',
  French: 'FR',
  Hungarian: 'HU',
  Indonesian: 'ID',
  Italian: 'IT',
  Japanese: 'JA',
  Korean: 'KO',
  Lithuanian: 'LT',
  Latvian: 'LV',
  Norwegian: 'NB',
  Dutch: 'NL',
  Polish: 'PL',
  Portuguese: 'PT',
  Romanian: 'RO',
  Russian: 'RU',
  Slovak: 'SK',
  Slovenian: 'SL',
  Swedish: 'SV',
  Turkish: 'TR',
  Ukrainian: 'UK',
  /** Same as `ChineseSimplified` */
  Chinese: 'ZH',
  ChineseSimplified: 'ZH',
  ChineseTraditional: 'ZH-HANT',
} as const;

export type Language = typeof languages[keyof typeof languages];
